### PR TITLE
chore(package.json) Fix V6 package.json file

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
The package.json file in v6 currently has merge conflict markers, this fix removes them

### CODE REVIEW

**Comment by nicolethoen** [comment]
I think the pr-preview action needs to be updated where ever there is a reference to (`origin/main` like on [this line](https://github.com/patternfly/react-topology/blob/c089767f56849d9b122d4990531b2a02ee415fb7/.github/workflows/pr-preview.yml#L18)) to be `origin/v6`.

**Comment by jeff-phillips-18** [comment]
> I think the pr-preview action needs to be updated where ever there is a reference to `origin/main` (like on [this line](https://github.com/patternfly/react-topology/blob/c089767f56849d9b122d4990531b2a02ee415fb7/.github/workflows/pr-preview.yml#L18)) to be `origin/v6`.

@nicolethoen I've updated `pr-preview.yml` for this PR but it doesn't see to be using it.

**Comment by nicolethoen** [comment]
ah - true - it wont run the new actions til the old ones are merged. You or I could make the changes to the gh action directly in the v6 branch.

**Comment by jeff-phillips-18** [comment]
@nicolethoen I think we just merge this PR. Then we can test the next, this PR only fixes a merge issue.

**Pull request merged**
