### PR TITLE
feat(pipelines): Add pipeline groups layout

### LINKED ISSUE #155: Support for Node Subgraph Layout with Dagre
**Describe the problem**
The topology pipelines components and layout should support nodes that draw another graph within them, similar to groups. This would include:

Updating the Dagre layout to programmatically calculate the bounds of the parent node based on the bounding box of its children (as per @jeff-phillips-18)

**What is your product and what release date are you targeting?**
RHOAI: sprint 2.10 (March 25 - April 2).
```[tasklist]
### Tasks
- [ ] Add DagreGroupLayout
- [ ] Update getEdgesFromNodes to handle groups of nodes
- [ ] https://github.com/patternfly/react-topology/issues/153
```

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## What
Closes #155 
Closes [RHOAIENG-4186](https://issues.redhat.com/browse/RHOAIENG-4186)

## Description
Adds a `DagreGroupsLayout` and `PipelineDagreGroupsLayout` which treats each group as its own layout. Groups are connected to tasks or other groups.

## Type of change
- [x] Feature

### Horizontal
image

### Vertical
image

/cc @andrewballantyne

## Surge
https://pipeline-groups.surge.sh/

### CODE REVIEW

**Review by jenny-s51 — CHANGES_REQUESTED** [review]
Group layouts look awesome @jeff-phillips-18 🎉

Wondering it if would make sense to update the default label positioning to "top" in order to align with the designs and visually distinguish where the groups begin... In the vertical example, the labels for Executions 1 and 2 are positioned over forks of edges so it's a bit tricky to figure out which series of nodes the execution label refers to. WDYT @jeff-phillips-18 ?

Screenshot 2024-03-05 at 9 47 37 AM

**Comment by andrewballantyne** [comment]
Question: You have a colour shift for the internal groups -- does this mean there are only allowed one layer of groups inside groups? If not, what does it look like if another group is inside the inner group?

**Comment by jeff-phillips-18** [comment]
> Question: You have a colour shift for the internal groups -- does this mean there are only allowed one layer of groups inside groups? If not, what does it look like if another group is inside the inner group?

@andrewballantyne the group background alternates:

image

**Comment by jeff-phillips-18** [comment]
> Wondering it if would make sense to update the default label positioning to "top"

@jenny-s51 Moved them to the top for vertical layout (this is in the app code not the toolkit)

image

**Comment by andrewballantyne** [comment]
Design wise this lgtm -- I didn't dive into the code.

**Review by jenny-s51 — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]
Looks good ran it locally with out any issues.  Code looks good.

**Pull request merged**
