### PR TITLE
Update to latest Patternfly V6 alphas

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## What
Updates to last Patternfly V6 alpha release.

## Type of change
- [x] Refactoring (no functional changes, no api changes)

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
There are 2 commits here:

1. run the v6 code mods
2. make fixes to get close

You can look at the second commit to see where the codemods fell short.

**Comment by jeff-phillips-18** [comment]
Demo app surge: https://v6-updates.surge.sh/

**Comment by nicolethoen** [comment]
@jeff-phillips-18 can I do anything to help move this along?

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson @nicolethoen @jenny-s51  Please take another look. I think this is in good shape now.

Latest surge for Demo app: https://v6-updates.surge.sh/

Surge for Doc app: https://react-topology-pr-topology-201.surge.sh/

**Review by andrew-ronaldson — COMMENTED** [review]
Looks good. Saw a couple things in review.

- Can you add a `border-radius: var(--pf-t--global--border--radius--medium);`  to the node groupings
- When there is a status modifier the node labels drop the status color border on hover.

Screenshot 2024-06-25 at 9 41 45 AM


- In pipelines can the expanded task look like this instead of the node group.

Screenshot 2024-06-25 at 9 59 40 AM

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson @jenny-s51 Updated. PTAL.

**Comment by andrew-ronaldson** [comment]
Looks good. I still see the hover/selected state bug on the node labels. We can fix that in another PR.

**Surge**
Status + hover:
Screenshot 2024-06-26 at 10 08 39 AM

Status+Selected + hover:
Screenshot 2024-06-26 at 10 04 01 AM

**Figma** 
Status + hover:
Screenshot 2024-06-26 at 10 07 52 AM

Status + Selected + hover:
Screenshot 2024-06-26 at 10 05 22 AM

**Review by jenny-s51 — COMMENTED** [review]
The styles are looking awesome @jeff-phillips-18 ! Just noticing the sidebar example window isn't rendering on the docs site (all the other demos look great) https://react-topology-pr-topology-201.surge.sh/topology/sidebar.

**Comment by jeff-phillips-18** [comment]
@andrew-ronaldson @jenny-s51 Updated. PTAL.

**Comment by jeff-phillips-18** [comment]
> Just noticing the sidebar example window isn't rendering on the docs site (all the other demos look great) https://react-topology-pr-topology-201.surge.sh/topology/sidebar.

@jenny-s51 The docs surge did not get updated. If you run locally you will see this fix.

**Comment by jenny-s51** [comment]
Sounds good @jeff-phillips-18 pulling it down to take a look

**Review by jenny-s51 — APPROVED** [review]
LGTM 👍

**Pull request merged**
