### PR TITLE
added property to set whether the outline is hull or rect

### PR DESCRIPTION
**Pull request by leandroberetta**
Closes https://github.com/patternfly/react-topology/issues/113

## Description
A new property in the DefaultGroup was added to set whether the outline of the group is hulled or rect.

## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by jeff-phillips-18** [comment]
@jenny-s51 @nicolethoen Could you PTAL?

**Review by jenny-s51 — COMMENTED** [review]
Thank you for your contribution @leandroberetta ! Visually this is looking good - just a couple of comments:

It looks like when shift+clicking+dragging a node, the default behavior should move it out of a group. When this new prop is added, I can no longer seem to move the node out of the group. Is this to be expected?

Nit: I'm also wondering since the hulled outline was already the default and these changes introduce the rectangular outline, should we rename it to something like `rectOutline` instead? I think semantically this makes more sense and we could just set `rectOutline` instead of setting manually the prop value to false, however this isn't a blocker.

cc @jeff-phillips-18 what do you think?

**Comment by jeff-phillips-18** [comment]
> Nit: I'm also wondering since the hulled outline was already the default and these changes introduce the rectangular outline, should we rename it to something like `rectOutline` instead? I think semantically this makes more sense and we could just set `rectOutline` instead of setting manually the prop value to false, however this isn't a blocker.

I'm in favor of the `hulledOutline` just sounds better to me even if it is the default but I could go either way.

**Comment by leandroberetta** [comment]
> Thank you for your contribution @leandroberetta ! Visually this is looking good - just a couple of comments:
> 
> It looks like when shift+clicking+dragging a node, the default behavior should move it out of a group. When this new prop is added, I can no longer seem to move the node out of the group. Is this to be expected?
> 
> Nit: I'm also wondering since the hulled outline was already the default and these changes introduce the rectangular outline, should we rename it to something like `rectOutline` instead? I think semantically this makes more sense and we could just set `rectOutline` instead of setting manually the prop value to false, however this isn't a blocker.
> 
> cc @jeff-phillips-18 what do you think?

@jenny-s51, thanks for the review, @jeff-phillips-18 helped me with the issue you reported.

**Review by jenny-s51 — APPROVED** [review]
Thank you @leandroberetta @jeff-phillips-18 latest changes LGTM 🚀

**Review by jeff-phillips-18 — APPROVED** [review]

**Pull request merged**
